root@89dc8df6256c:/app# bash /tests/run-tests.sh; tmux wait -S done
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl4t64
The following NEW packages will be installed:
  curl libcurl4t64
0 upgraded, 2 newly installed, 0 to remove and 46 not upgraded.
Need to get 567 kB of archives.
After this operation, 1481 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libcurl4t64 amd64 8.5.0-2ubuntu10.6 [341 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 curl amd64 8.5.0-2ubuntu10.6 [226 kB]
Fetched 567 kB in 1s (617 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcurl4t64:amd64.
(Reading database ... 35702 files and directories currently installed.)
Preparing to unpack .../libcurl4t64_8.5.0-2ubuntu10.6_amd64.deb ...
Unpacking libcurl4t64:amd64 (8.5.0-2ubuntu10.6) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_8.5.0-2ubuntu10.6_amd64.deb ...
Unpacking curl (8.5.0-2ubuntu10.6) ...
Setting up libcurl4t64:amd64 (8.5.0-2ubuntu10.6) ...
Setting up curl (8.5.0-2ubuntu10.6) ...
Processing triggers for libc-bin (2.39-0ubuntu8.4) ...
downloading uv 0.7.13 x86_64-unknown-linux-gnu
no checksums to verify
installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
Initialized project `app`
Using CPython 3.12.3 interpreter at: /usr/bin/python3.12
Creating virtual environment at: .venv
Resolved 7 packages in 150ms
Prepared 5 packages in 152ms
Installed 5 packages in 56ms
 + iniconfig==2.1.0
 + packaging==25.0
 + pluggy==1.6.0
 + pygments==2.19.2
 + pytest==8.4.1
===================================================================== test session starts ======================================================================
platform linux -- Python 3.12.3, pytest-8.4.1, pluggy-1.6.0
rootdir: /tests
collected 0 items / 1 error

============================================================================ ERRORS ============================================================================
_______________________________________________________________ ERROR collecting test_outputs.py _______________________________________________________________
/tests/test_outputs.py:81: in <module>
    test_expect()
/tests/test_outputs.py:76: in test_expect
    assert "42" in actual_output.split("echo $?")[1], (
E   AssertionError: Expected '42' to be in expected.txt
E   assert '42' in '\n\n127\n\n~ # '
=================================================================== short test summary info ====================================================================
ERROR ../tests/test_outputs.py - AssertionError: Expected '42' to be in expected.txt
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 error in 5.12s =======================================================================
root@89dc8df6256c:/app#
